@extends('layouts.app')

@section('title', 'Customer List' )

{{-- @section('sidebar')
@parent

<p>This is appended to the master sidebar.</p>
@endsection --}}

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-header card-header-info d-flex justify-content-between align-items-center">
                    <div>
                        <h4 class="card-title">Codes Status</h4>
                        <p class="card-category">New employees on 15th September, 2016</p>
                    </div>
                    <div>
                        <a href="{{ route('code.create') }}" class="btn btn-primary btn-sm">Generate Codes</a>
                    </div>
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-hover">
                        <thead class="text-info">
                            <tr>
                                <th scope="col">Id</th>
                                <th scope="col">Code</th>
                                <th scope="col">Generated By</th>
                                <th scope="col">Used By</th>
                                <th scope="col">Status</th>
                                <th scope="col">Function</th>
                              </tr>
                            </thead>
                            <tbody>
                                @foreach ($codes as $code)
                                    <tr>
                                        <th scope="row">{{ $code->id }}</th>
                                        <td>{{ $code->code }}</td>
                                        <td>{{ $code->user->name }}</td>
                                        <td>N/A MUNA. CHECK THIS</td>
                                        <td>{{ ($code->status == 1) ? 'Available' : 'Not Available' }}</td>
                                        <td><a href="{{ route('code.show', $code->id) }}" class="btn btn-info btn-sm">View</a></td>
                                    </tr>
                                @endforeach
                        </tbody>
                      </table>
                </div>
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                      <li class="page-item {{ ($codes->currentpage() == 1) ? 'disabled' : ''}}">
                        <a class="page-link" href="{{ $codes->previousPageUrl() }}" tabindex="-1" aria-disabled="true" >Previous</a>
                      </li>
                        <li class="page-item disabled"><a href="#" class="page-link">{{ $codes->currentpage() }}</a></li>
                      <li class="page-item {{ ($codes->lastpage() == $codes->currentpage()) ? 'disabled' : ''}}">
                        <a class="page-link" href="{{ $codes->nextPageUrl() }}">Next</a>
                      </li>
                    </ul>
                  </nav>
            </div>
        </div>
    </div>

    
    </div>
@endsection


